# Generated by Django 3.0.6 on 2020-05-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="log", options={"ordering": ["-created_at"]},
        ),
    ]
