# Generated by Django 2.2 on 2020-06-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200529_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
